=== AzaharaFE/LenguajesActividad2/XML-DTD/XML-XSD/biblioteca.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
    <element name="biblioteca">
        <complexType>
            <sequence>
                <element name="libros">
                    <complexType>
                        <sequence>
                            <element name="libro" minOccurs="1" maxOccurs="unbounded">
                                <complexType>
                                    <sequence>
                                        <element name="titulo" type="string"></element>
                                        <element name="capitulos">
                                            <complexType>
                                                <sequence>
                                                    <element name="capitulo" minOccurs="1" maxOccurs="unbounded">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="titulo" type="string"></element>
                                                                <element name="Contenido">
                                                                    <complexType>
                                                                        <attribute name="enlace" type="string"></attribute>
                                                                    </complexType>
                                                                </element>
                                                            </sequence>
                                                            <attribute name="NumeroCapitulo" type="string"></attribute>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                        <element name="indice" type="string"></element>
                                        <element name="sinopsis" type="string"></element>
                                    </sequence>
                                    <attribute name="id" use="required">
                                        <simpleType>
                                                <restriction base="ID">
                                                    <pattern value="L[0-9]{4}"></pattern>
                                                </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name="Tipo_clase" use="required">
                                        <simpleType>
                                                <restriction base="string">
                                                    <enumeration value="Novela"></enumeration>
                                                    <enumeration value="Infantil"></enumeration>
                                                    <enumeration value="Didactico"></enumeration>
                                                </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name="NumeroPaginas" type="integer"></attribute>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <element name="revistas">
                    <complexType>
                        <sequence>
                            <element name="revista" minOccurs="1" maxOccurs="unbounded">
                                <complexType>
                                    <sequence>
                                        <element name="titulo" type="string"></element>
                                        <element name="NumeroRevista" type="integer"></element>
                                        <element name="indice" type="string"></element>
                                        <element name="Secciones">
                                            <complexType>
                                                <sequence>
                                                    <element name="Seccion" minOccurs="1" maxOccurs="unbounded">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="titulo" type="string"></element>
                                                                <element name="Contenido">
                                                                    <complexType>
                                                                        <attribute name="enlace" type="string"></attribute>
                                                                    </complexType>
                                                                </element>
                                                            </sequence>   
                                                            <attribute name="NumeroPaginas" use="required"></attribute>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>    
                                         <attribute name="id" use="required">
                                        <simpleType>
                                                <restriction base="ID">
                                                    <pattern value="R[0-9]{4}"></pattern>
                                                </restriction>
                                        </simpleType>
                                    </attribute>
                                         <attribute name="Tipo_clase" use="required">
                                                 <simpleType>
                                                     <restriction base="string">
                                                         <enumeration value="Informatica"></enumeration>
                                                         <enumeration value="Corazon"></enumeration>
                                                         <enumeration value="Coches"></enumeration>
                                                         <enumeration value="Investigacion"></enumeration>
                                                         <enumeration value="Otras"></enumeration>
                                                      </restriction>
                                                 </simpleType>
                                            </attribute>
                                         <attribute name="NumeroPaginas" use="required"></attribute>
                                </complexType>     
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <element name="periodicos">
                    <complexType>
                        <sequence>
                            <element name="periodico" minOccurs="1" maxOccurs="unbounded">
                                <complexType>
                                    <sequence>
                                        <element name="indice" type="string"></element>
                                        <element name="seccion_periodico">
                                            <complexType>
                                                <sequence>
                                                    <element name="articulos" minOccurs="1" maxOccurs="unbounded">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="articulo">
                                                                    <complexType>
                                                                        <sequence>
                                                                            <element name="Contenido">
                                                                                <complexType>
                                                                                    <attribute name="enlace" type="string"></attribute>
                                                                                </complexType>
                                                                            </element>
                                                                        </sequence>
                                                                        <attribute name="autor" type="string" use="required"></attribute>
                                                                    </complexType>
                                                                </element>
                                                            </sequence>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                                <attribute name="tipoSeccion" use="required">
                                                    <simpleType>
                                                        <restriction base="string">
                                                            <enumeration value="Economica"></enumeration>
                                                            <enumeration value="Opinion"></enumeration>
                                                            <enumeration value="Deportes"></enumeration>
                                                            <enumeration value="Nacional"></enumeration>
                                                            <enumeration value="Internacional"></enumeration>
                                                        </restriction>
                                                    </simpleType>
                                                </attribute>
                                            </complexType>
                                        </element>
                                    </sequence>
                                    <attribute name="id" use="required">
                                            <simpleType>
                                                <restriction base="ID">
                                                    <pattern value="P[0-9]{4}"></pattern>
                                                </restriction>
                                            </simpleType>
                                    </attribute>
                                    <attribute name="Tipo_clase" use="required">
                                            <simpleType>
                                                <restriction base="string">
                                                    <enumeration value="Nacionales"></enumeration>
                                                    <enumeration value="Internacionales"></enumeration>
                                                </restriction>
                                            </simpleType>
                                    </attribute>
                                    <attribute name="FechaPublicacion" type="string" use="required"></attribute>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== AzaharaFE/LenguajesActividad2/XSD-XML/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="biblioteca.xsd">   
        <libros>
         <libro id="L1111" Tipo_clase="Novela" NumeroPaginas="0">
                <titulo>Nombre libro</titulo>
                        <capitulos>
                                <capitulo NumeroCapitulo="0">
                                        <titulo>Nombre capitulo</titulo>
                                        <Contenido enlace="enlace.html"/>
                                </capitulo>
                        </capitulos> 
                <indice/>
                <sinopsis/>
         </libro>          
         <libro id="L2222" Tipo_clase="Infantil" NumeroPaginas="0">
                <titulo>Nombre libro</titulo>
                        <capitulos>
                                <capitulo NumeroCapitulo="0">
                                        <titulo>Nombre capitulo</titulo>
                                        <Contenido enlace="enlace.html"/>
                                </capitulo>
                        </capitulos> 
                <indice/>
                <sinopsis/>
         </libro>          
         <libro id="L3333" Tipo_clase="Didactico" NumeroPaginas="0">
                <titulo>Nombre libro</titulo>
                        <capitulos>
                                <capitulo NumeroCapitulo="0">
                                        <titulo>Nombre capitulo</titulo>
                                        <Contenido enlace="enlace.html"/>
                                </capitulo>
                        </capitulos> 
                <indice/>
                <sinopsis/>
         </libro>          
        </libros>
        <revistas> 
          <revista id="R0001" Tipo_clase="Informatica" NumeroPaginas="0">
                 <titulo>Nombre revista</titulo>
                 <NumeroRevista>0</NumeroRevista>
                 <indice/>
                 <Secciones>
                        <Seccion NumeroPaginas="">
                                <titulo>nombre seccion</titulo> 
                                <Contenido enlace="enlace.html"/>
                        </Seccion>
                 </Secciones>
          </revista>
          <revista id="R0002" Tipo_clase="Corazon" NumeroPaginas="0">
                 <titulo>Nombre revista</titulo>
                 <NumeroRevista>0</NumeroRevista>
                 <indice/>            
                 <Secciones>
                        <Seccion NumeroPaginas="">
                                <titulo>nombre seccion</titulo> 
                                <Contenido enlace="enlace.html"/>
                        </Seccion>
                 </Secciones>
          </revista>
          <revista id="R0003" Tipo_clase="Coches" NumeroPaginas="0">
                 <titulo>Nombre revista</titulo>
                 <NumeroRevista>0</NumeroRevista>
                 <indice/>
                 <Secciones>
                        <Seccion NumeroPaginas="">
                                <titulo>nombre seccion</titulo> 
                                <Contenido enlace="enlace.html"/>
                        </Seccion>
                 </Secciones>
          </revista>
          <revista id="R0004" Tipo_clase="Investigacion" NumeroPaginas="0">
                 <titulo>Nombre revista</titulo>
                 <NumeroRevista>0</NumeroRevista>
                 <indice/>
                 <Secciones>
                        <Seccion NumeroPaginas="">
                                <titulo>nombre seccion</titulo> 
                                <Contenido enlace="enlace.html"/>
                        </Seccion>
                 </Secciones>
          </revista>
          <revista id="R0005" Tipo_clase="Otras" NumeroPaginas="0">
                 <titulo>Nombre revista</titulo>
                 <NumeroRevista>0</NumeroRevista>
                 <indice/>
                 <Secciones>
                        <Seccion NumeroPaginas="">
                                <titulo>nombre seccion</titulo> 
                                <Contenido enlace="enlace.html"/>
                        </Seccion>
                 </Secciones>
          </revista>
        </revistas>   
        <periodicos>
          <periodico id="P4444" Tipo_clase="Nacionales" FechaPublicacion="">
                 <indice/>
                 <secciones>
                 <seccion_periodico tipoSeccion="Economica">
                                <articulos>
                                        <articulo autor="nombreAutor">
                                                <Contenido enlace="enlace.html"/>
                                        </articulo>
                                </articulos>
                 </seccion_periodico> 
                 <seccion_periodico tipoSeccion="Opinion">
                                <articulos>
                                        <articulo autor="nombreAutor">
                                                <Contenido enlace="enlace.html"/>
                                        </articulo>
                                </articulos>
                 </seccion_periodico> 
                 <seccion_periodico tipoSeccion="Deportes">
                                <articulos>
                                        <articulo autor="nombreAutor">
                                                <Contenido enlace="enlace.html"/>
                                        </articulo>
                                </articulos>
                 </seccion_periodico> 
                 <seccion_periodico tipoSeccion="Nacional">
                                <articulos>
                                        <articulo autor="nombreAutor">
                                                <Contenido enlace="enlace.html"/>
                                        </articulo>
                                </articulos>
                 </seccion_periodico> 
                 <seccion_periodico tipoSeccion="Internacional">
                                <articulos>
                                        <articulo autor="nombreAutor">
                                                <Contenido enlace="enlace.html"/>
                                        </articulo>
                                </articulos>
                 </seccion_periodico> 
                 </secciones>
          </periodico>    
          <periodico id="P5555" Tipo_clase="Internacionales" FechaPublicacion="">
                 <indice/>
                 <secciones>
                        <seccion_periodico tipoSeccion="Economica">
                                <articulos>
                                        <articulo autor="nombreAutor">
                                                <Contenido enlace="enlace.html"/>
                                        </articulo>
                                </articulos>
                        </seccion_periodico> 
                        <seccion_periodico tipoSeccion="Opinion">
                                <articulos>
                                        <articulo autor="nombreAutor">
                                                <Contenido enlace="enlace.html"/>
                                        </articulo>
                                </articulos>
                        </seccion_periodico> 
                        <seccion_periodico tipoSeccion="Deportes">
                                <articulos>
                                        <articulo autor="nombreAutor">
                                                <Contenido enlace="enlace.html"/>
                                        </articulo>
                                </articulos>
                        </seccion_periodico> 
                        <seccion_periodico tipoSeccion="Nacional">
                                <articulos>
                                        <articulo autor="nombreAutor">
                                                <Contenido enlace="enlace.html"/>
                                        </articulo>
                                </articulos>
                        </seccion_periodico> 
                        <seccion_periodico tipoSeccion="Internacional">
                                <articulos>
                                        <articulo autor="nombreAutor">
                                                <Contenido enlace="enlace.html"/>
                                        </articulo>
                                </articulos>
                        </seccion_periodico> 
                </secciones>
         </periodico>               
        </periodicos>   
</biblioteca>
